[TOC]

# 错误处理、调试和测试

## Error

### 同步操作的 try-catch

`try` 定义在执行时进行错误测试的代码块。

`catch` 定义当 try 代码块发生错误时，所执行的代码块。二者是成对出现的。

`throw` 抛出自定义错误，可以是字符串、数字、逻辑值或对象。

`finally` 在 try 和 catch 语句之后，==无论是否有触发异常，该语句都会执行==。

==try-catch-throw 捕获不到异步操作中发生的异常==。

```
try {
    ...    //异常的抛出
} catch(e) {
    ...    //异常的捕获与处理
} finally {
    ...    //结束处理
}
```

```javascript
// 预定义错误
let txt="";
function message(){
	try {
		adddlert("Welcome guest!");
	}
	catch(err) {
		txt="本页有一个错误。\n\n";
		txt+="错误描述：" + err.message + "\n\n";
		txt+="点击确定继续。\n\n";
		alert(txt);
	}
}
```

```html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>自定义错误</title>
</head>

<body>
    <p>不管输入是否正确，输入框都会再输入后清空。</p>
    <p>请输入 5 ~ 10 之间的数字：</p>

    <input id="demo" type="text">
    <button type="button" onclick="myFunction()">点我</button>

    <p id="p01"></p>

    <script>
        function myFunction() {
            var message, x;
            message = document.getElementById("p01");
            message.innerHTML = "";
            x = document.getElementById("demo").value;
            try {
                if (x.replace(/(^\s*)|(\s*$)/g, "") === "") throw "值是空的";
                if (isNaN(x)) throw "值不是一个数字";
                x = Number(x);
                if (x > 10) throw "太大";
                if (x < 5) throw "太小";
                message.innerHTML = "合法输入。";
            } catch (err) {
                message.innerHTML = "错误: " + err + "。";
            } finally {
                document.getElementById("demo").value = "";
            }
        }
    </script>

</body>

</html>
```

### 异步操作判断 error.code

error-first：回调函数的第一个参数普遍为 error 对象









## 调试（Debug）

### 在浏览器中调试

F12打开开发者工具。

#### Elements

实时DOM结构。

#### Console

控制台，显示日志。

#### Sources

##### 功能区

左侧窗口为项目结构

中间窗口为源代码，打开 js 文件或html文件的 js 语句区，可以设置单击行号左侧设置断点（Breakpoints）

右侧窗口的Global可以监控所有变量

##### 调试

1. JavaScript 中的`debugger`关键字用于使JavaScript在这一行停止执行，并==调用调试函数==。这与在调试工具中设置断点的效果是一样的。如果没有调试可用，debugger 语句将无法工作。

2. 刷新页面，程序运行到断点暂停，如果这里是一个函数，按F11（Step into next function call）

- Call Stack（调用堆栈）将显示进入了这个函数。
- Scope（作用域）中出现 Local，包含作用域内部的变量

2. 条件断点
   1. 已经设置了断点的行，右键断点编辑，可以在满足条件时才暂停程序

### Node.js 调试

## 测试

### 优质测试的三个特性

可重复性

简易性

独立性，尽可能集成到最小的单元

### 手动测试

手动测试可以在类似[HTML/CSS/JS 在线工具 | 菜鸟工具 (runoob.com)](http://c.runoob.com/front-end/61)的页面上进行。但如果测试用例很多，手动测试是非常繁琐的。

### 自动化测试

自动化测试利用一些第三方库实现，实现定义好一系列（实际是大量的，尽量覆盖各种各样的可能）输入和输出的对应关系。每次修改代码后，都以各种方式运行测试函数，查看实际运行结果是否满足预设的效果。

```javascript
//每次修改pow()，都运行下面的测试函数，检查输入和输出是否相等
describe("Raises x to power n", function() {
  it("5 in the power of 1 equals 5", function() {
    assert.equal(pow(5, 1), 5);
  });

  it("5 in the power of 2 equals 25", function() {
    assert.equal(pow(5, 2), 25);
  });

  it("5 in the power of 3 equals 125", function() {
    assert.equal(pow(5, 3), 125);
  });
});
```



#### 断言 assert

自定义一个 report 函数来显示成功、失败的信息

```javascript
// assert.js

function assert(value, text) { // 每个测试返回value和text信息，然后传递给 assert 函数来显示
  let li = document.createElement("li"); // 为每条信息创建一个 li 节点
  li.className = value ? "pass" : "fail"; // 根据成功失败分类，用不同颜色显示
  li.appendChild(document.createTextNode(text));
  let results = document.getElementById("results");
  if (!results) { // 若ul#result不存在，就现造一个
    results = document.createElement("ul");
    results.setAttribute('id', 'results');
    document.body.appendChild(results);
  }
  results.appendChild(li);
}

function pass(text) { assert(true, text); }
function fail(text) { assert(false, text); }
function report(text) { pass(text); }
```



```css
/* assert.css */

body {
  font-family: sans-serif;
  font-size: 12pt;
}

#results {
  background-color: #e0e0e0;
  border-radius: 1em;
  padding: 1em;
  list-style-position: inside;
}

#results li {
  margin-bottom: 0.2em;
}

#results li.pass {
  /* pass 类的消息显示为绿色 */
  color: green;
}

#results li.fail {
  /* fail 类的消息显示为红色 */
  color: red;
  text-decoration: line-through;
}
```







